### ISSUE TITLE
logs in '/var/log/messages' are not rotated anymore, some bosh releases are running out of disk space

### ISSUE THREAD

**Issue by KaiHofstetter** [cloudfoundry/bosh-linux-stemcell-builder#116]
With the [PR "make rsyslog and logrotate configs consistent'](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/110) the logrotation configuration for the folder '/var/log/messages' has been removed.

Some bosh releases still rely on the rotation of log files in this folder and are now running out of disk space.

I'm not 100% sure why this configuration has been removed and why it is related to the mentioned 'CIS level 1 Rule 4.3'.

**Comment by turtschan** [comment]
I noticed a logrotate bug on CentOS (bosh-openstack-kvm-centos-7-go_agent-raw/3763.61).

The rotated file (`messages.1`) is still opened by rsyslog instead of the new logfile (`messages`) and thus grows to infinity: 

```
# lsof | grep messages
abrt-watc   742                       root    4r      REG              252,1         0      36663 /var/log/messages
rsyslogd   2164                     syslog    8w      REG              252,3  85347042     522247 /var/log/messages.1
in:imuxso  2164  2198               syslog    8w      REG              252,3  85347042     522247 /var/log/messages.1
in:imklog  2164  2199               syslog    8w      REG              252,3  85347042     522247 /var/log/messages.1
rs:main    2164  2200               syslog    8w      REG              252,3  85347042     522247 /var/log/messages.1

```

`postrotate` in `/etc/logrotate.d/rsyslog` contains a none-existent pid file (`/var/run/rsyslogd.pid`).

`systemctl kill -s HUP rsyslog.service` and `kill -SIGHUP $(cat /var/run/syslogd.pid)` work like expected.

**Comment by friegger** [comment]
In #75 /var/log/messages had been excluded for Ubuntu and /var/log/syslog for Centos. Consequently log rotation had been removed as well. Also centos support has been dropped at some point time. Closing this one.
