### ISSUE TITLE
GCC version out of date

### ISSUE THREAD

**Issue by jraverdy-orange** [cloudfoundry/bosh-linux-stemcell-builder#21]
gcc version provided by stemcell is out of date and disallow compilation of recent packages (for exemple mongodb >3.2 needs at least gcc 5.3)
The recompilation from gcc sources in a package takes arround 1hour, so it should be a good thing if a more recent version of gcc could be embedded directly in bosh stemcellgcc version provided by stemcell is out of date and disallow compilation of recent packages (for exemple mongodb >3.2 needs at least gcc 5.3)
The recompilation from gcc sources in a package takes arround 1hour, so it should be a good thing if a more recent version of gcc could be embedded directly in bosh stemcell

**Comment by cppforlife** [comment]
@jraverdy-orange we include ubuntu packages from their official apt repo. it appears that both ubuntu trusty and xenial ship gcc 3.3. since we are not maintaining any external sources, whatever ubuntu provide is what's being included.

i would recommend to include already built mongodb binaries as blobs in your release, instead of trying to compile them from scratch.
