### ISSUE TITLE
vim defaults broken on jammy

### ISSUE THREAD

**Issue by domdom82** [cloudfoundry/bosh-linux-stemcell-builder#239]
While testing jammy I've noticed this bug:
```
# vim
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

There is an upstream discussion about the issue here:

https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg6018994.html

I've opened this issue to track / possibly fix the upstream issue as it severely hampers productivity with jammy stemcells.

**Comment by ramonskie** [comment]
the bug is confirmed at canonical see https://bugs.launchpad.net/ubuntu/+source/vim/+bug/1968912
a workaround would be to add the `vim-runtime` package

as vim-tiny is installed by default and when installing `vim-runtime` its not tiny vim anymore ;)

or we wait until canonical fixed there vim-common package

**Comment by ramonskie** [comment]
a new suggestion was made 
```
So a quick fix would be:
$ sudo touch /usr/share/vim/vim82/defaults.vim
```
