### ISSUE TITLE
aws-ubuntu-xenial light-stemcell 315.64 version gone

### ISSUE THREAD

**Issue by kwonsoonwoo** [cloudfoundry/bosh-linux-stemcell-builder#256]
I have a question for you.
The cf deployment I manage is based on aws-ubuntu-xenial version 315.64 stemcell.

But the 315.64 version of the stemcell ami disappeared from the aws region.
ami only has version 621.92 or higher.

Difficult to change because cf-deployment is already built.
What should I do in this case?

**Comment by ramonskie** [comment]
yes the 315 version has been cleaned up as they are more than 3 years old.
it should be easy to upgrade to the latest 621 as there is not much difference except the bosh-agent version.
also not that the 621 version has also not been updated for more than 2 years and that xenial has been EOL since 2021
so i would suggest on update

**Comment by rkoster** [comment]
Stemcells older then 3 years will be removed per: https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0010-stemcell-cleanup.md#proposal
