### ISSUE TITLE
Why JJ stemcell customize cgroup into hybrid mode

### ISSUE THREAD

**Issue by YanzhaoLi** [cloudfoundry/bosh-linux-stemcell-builder#262]
Ubuntu 22.04 from cononical by default uses the cgroup v2. 
But we noticed that the JJ stemcell customized the `"systemd.unified_cgroup_hierarchy=false"` opition to use hybrid mode in this commit: https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/bbae678fe3727bde9bc843a94f24004d8642c058 
Could you please help explain the reason? 

I am asking because kubernetes detects cgroup version by only checking `/sys/fs/cgroup` instead of `/sys/fs/cgroup/unified`

**Comment by rkoster** [comment]
`runc fully supports cgroup v2 (unified mode) since v1.0.0-rc93.`: https://github.com/opencontainers/runc/blob/main/docs/cgroup-v2.md
supported by bpm since: https://github.com/cloudfoundry/bpm-release/releases/tag/v1.1.10 with rc94
used in garden runc since: https://github.com/cloudfoundry/garden-runc-release/commit/98d758d3e7b3294bb293675a2ab13435969f327d since version [v1.19.26](https://github.com/cloudfoundry/garden-runc-release/releases/tag/v1.19.26)

**Comment by rkoster** [comment]
@YanzhaoLi is this issue blocking or are their ways to work around this with k8s

**Comment by rkoster** [comment]
@YanzhaoLi  I'm gonna close this issue, feel free to reopen it when needed.

**Comment by poblin-orange** [comment]
Hello @rkoster 
currently hitting this issue. tracking our analysis here wrt k8s (k3s). https://github.com/orange-cloudfoundry/paas-templates/issues/1974

As far as i know, Hybrid mode is a transition / legacy mode we should get rid off.
Any reason the stemcell could settle for full v2?

thks for your insight

**Comment by rkoster** [comment]
@ameowlia could you check with the garden maintainers to check if they would consider this a breaking change? If so this would require us the create a new stemcell line, which is hugely expensive.

**Comment by ramonskie** [comment]
noble will move to cgroup v2

**Comment by ramonskie** [comment]
see #327
