### ISSUE TITLE
[task] pre-work 24.04 lts stemcell release

### ISSUE THREAD

**Issue by ramonskie** [cloudfoundry/bosh-linux-stemcell-builder#294]
as ubuntu lts releases are created every 2 years. we should also keep up with there release cycle.
its still a year away. but maby we need to do some pre-work
investigate and readup  on the changes to come for 23.04/10

**Comment by pburkholder** [comment]
I thought the point of jumping to 22.04 was to stick with that until 26.04. If CF runs only on newer stemcells, FIPS compliance will always be out of reach.

**Comment by max-soe** [comment]
The question is how long can we support the older versions? Can we provide the complete stack on 2 or 3 stemcells before their standard support ends?
I think the idea to keep up with the release cycle is to have easier migrations right? Further the community have more time to migrate because if we use every second release we only have one year between release of the new version and end of standard support of the old version. If we provide every major version the community have more time to migrate, but then we must support 2 or 3 versions in parallel.

**Comment by beyhan** [comment]
What @max-soe mentioned is one of the issues we noticed with the four years cycle. Regarding FIPS it is also a challenge because Ubuntu Bionic is EoL but there is no FIPS certified Ubuntu Jammy. With a two years cycle the users could stay on the old FIPS certified stemcell line until the new one gets it, which we hope will be before EoL of the old one. This is a discussion which have to happen in the CFF community via an RFC so that we have a decision. There is nothing concrete yet.

**Comment by ramonskie** [comment]
there will always only be 2 LTS releases supported within the support window of canonical 
so the max ammount of stemcells lines we are going to support are 2.
the same as we did with bionic/jammy.
bionic is now EOL so now we only maintain for 1 year just 1 stemcell line until the next LTS version is available again.

so the idea is to keep up to date with all the supported LTS releases. which will be max 2 at a time.

as beyhan mentioned FIPS is a thing on its own and will have different release cycles. pipelines etc,

**Comment by max-soe** [comment]
Between bionic and jammy there is also [Focal Fossa](https://wiki.ubuntu.com/FocalFossa). So if we now update every 2 years, we must support 3 LTS.

**Comment by beyhan** [comment]
We have different options here and we should analyse all of them and compare but I don't think that this issue is the right place. I will prefer an RFC for this so that we get more brother feedback.

**Comment by ramonskie** [comment]
this can be closed see cloudfoundry/community#892
