### ISSUE TITLE
Customizing stem cell

### ISSUE THREAD

**Issue by nsharmacovs** [cloudfoundry/bosh-linux-stemcell-builder#32]
Is there a documentation which tell use how to modify stem cell and rebuild it for ubuntu ?
  name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  version: '3312.49'

**Comment by tjvman** [comment]
@nsharmacovs What do you need to modify about the stemcell?

**Comment by nsharmacovs** [comment]
i wanted to update  /etc/resolv.conf with few options like 
options rotate timeout:1 retries:1

but i am unable to figure out if i should be updating stem cell or anything else ..

I am new to CF .

**Comment by dpb587-pivotal** [comment]
Hi - I would recommend trying out CF with the default, recommended settings first. Particularly because [cf-deployment](https://github.com/cloudfoundry/cf-deployment) has options to use the newer BOSH DNS component which acts as a local recursor and handles lightweight caching.

Are you seeing a specific error which is requiring this change? Are you trying to reach parity with an existing environment?

Stemcells are difficult to maintain long-term, and to ensure a consistent environment for releases, it will be best if you're able to use the stemcells we officially provide from [bosh.io/stemcells](https://bosh.io/stemcells).

This does sound related to https://github.com/cloudfoundry/os-conf-release/issues/26.

**Comment by dpb587-pivotal** [comment]
Closing - feel free to continue the discussion and respond in https://github.com/cloudfoundry/bosh/issues/1910.
