### ISSUE TITLE
[xenial] Could not execute 'apt-key' to verify signature

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-linux-stemcell-builder#39]
Inside a xenial 1.97 vm I tried to run `apt-get update` and got the errors:

```
Err:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Err:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
```

The solution from https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1577926 was to first run:

```
chmod 1777 /tmp
```

Perhaps `/tmp` needs these settings permanently; or am I doing something wrong?

**Comment by cppforlife** [comment]
@drnic which user are you running this as?

**Comment by drnic** [comment]
@cppforlife its running inside `packaging` script within a compilation VM, so `root` user I assume

**Comment by drnic** [comment]
Confirmed, also get this on normal vms running commands as root:

```
# sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
0% [1 InRelease gpgv 247 kB] [Waiting for headers] [Waiting for headers]Couldn't create tempfiles for splitting up /var/lib/apt/lists/archive.ubuntu.com_ubuntErr:1 http://archive.ubuntu.com/ubuntu xenial InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [107 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
0% [2 InRelease gpgv 107 kB] [3 InRelease 63.4 kB/109 kB 58%]Couldn't create tempfiles for splitting up /var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_Err:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Err:3 http://archive.ubuntu.com/ubuntu xenial-updates InReleaseting up /var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_xenial-updates_InRelease
  Could not execute 'apt-key' to verify signature (is gnupg installed?)
Fetched 216 kB in 0s (309 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu xenial InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://security.ubuntu.com/ubuntu xenial-security InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://archive.ubuntu.com/ubuntu xenial-updates InRelease: Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial/InRelease  Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/xenial-updates/InRelease  Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: Failed to fetch http://security.ubuntu.com/ubuntu/dists/xenial-security/InRelease  Could not execute 'apt-key' to verify signature (is gnupg installed?)
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by cppforlife** [comment]
will file ticket with canonical to see what they think...

**Comment by cppforlife** [comment]
was filed as https://support.canonical.com/ua/s/case/500D000001hfYHIIA2/aptget-update-does-not-work

there was a problem wiht our canonical support accounts.

**Comment by gerhard** [comment]
I was still getting this in **bosh-google-kvm-ubuntu-xenial-go_agent/97.12**, running apt with this option fixed the error for me: `apt -o APT::Sandbox::User=root update`

I've also noticed some expired keys in `apt-key list` and deleted them via `apt-key del $EXPIRED_KEY_ID`

**Comment by flavorjones** [comment]
@cppforlife I'm curious if Canonical got back to you? I've run into this as well. Anything I can do to help support?

**Comment by flavorjones** [comment]
Ah, I see this has been picked up in https://www.pivotaltracker.com/n/projects/2197707/stories/161025696

:thumbsup:

**Comment by dpb587-pivotal** [comment]
Canonical's suggestion in the support case was to try using `chmod 1777 /tmp`. 

For what it's worth, our current `chmod 0770 /tmp` was introduced in the [first commit](https://github.com/cloudfoundry/bosh/commit/519b8a686a878fc34b7d2af9231cf8077330cb82#diff-e0c827344a9f1a53b5d83dafc9ecb3d0) of the stemcell builder code in 2012. It seems the original intent was to "lock down" usage of `/tmp` to force processes to use `/var/vcap/data/tmp` instead. The phrasing of the code comment around it makes me wonder if the original goal was to discover components/apps which still need to be migrated away from referencing `/tmp` (rather than a specific security/hardening concern).

I see the related [Launchpad bug](https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1577926) about this is still marked as Confirmed. I suspect it's an upstream change of behavior, but probably a low priority from their perspective. Especially given the lack of community comments on the bug, relatively few people following the bug, and uncommon environment requirements.

At this time, it looks like the story is several weeks out in our backlog.

**Comment by voelzmo** [comment]
> It seems the original intent was to "lock down" usage of /tmp to force processes to use /var/vcap/data/tmp instead. 

since then, it seems that we've changed our opinion a bit: we have even mounted `/tmp` to the ephemeral disk as well, such that you get additional storage. It seems that Canonical won't fix this issue anytime soon, so probably our best chance of making `apt-get` possible on xenial stemcells is changing the permissions, right?

**Comment by mrosecrance** [comment]
Fixed in https://www.pivotaltracker.com/n/projects/2197707/stories/161025696
