### ISSUE TITLE
faillog command can't work on Xenial stemcell 

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-linux-stemcell-builder#56]
See the error below in the new Xenial stemcell:

```
# faillog
faillog: Cannot open /var/log/faillog: No such file or directory
```

The workaround is to create an empty file `/var/log/faillog` with 600 permission, please help check why there isn't `/var/log/faillog` in base image? Thanks.

/cc @maximilien

**Comment by dpb587-pivotal** [comment]
Good find - I've created [Story #159169269](https://www.pivotaltracker.com/story/show/159169269); we'll discuss and prioritize it soon.

**Comment by dpb587-pivotal** [comment]
We looked into this as part of the story, but it looks like `/var/log/faillog` is not something which is supported in Trusty or Xenial. Instead, `pam_tally2` is being used by the auth configuration, and it is responsible for managing `/var/log/tallylog`.

It's worth noting that the `/var/log/tallylog` file does not exist by default, so if you run the `pam_tally2` command, it will error with the following if there have been no failed attempts...

```
# pam_tally2
pam_tally2: No such file or directory
```

But, once you have, the output should work as expected.

```
# pam_tally2
Login           Failures Latest failure     From
rstallman           2    08/17/18 20:44:58  /dev/pts/0
```

Since the default Ubuntu install does not provision this log file, we're not too concerned about that initial error, especially considering there's no data loss and doesn't mean a security issue. Creating the `/var/log/faillog` file does help avoid the `no such file` error, but it should not be impacting how or where login events are being logged.

Was there a particular dependency you had on `faillog`, and are you saying behavior changed from Ubuntu Trusty? From what we can tell, Trusty is operating the same.

Originally I was confusing `faillog` with `faillock`, which deals with locking accounts after a given period; but I think that is unrelated to this.

@dpb587-pivotal && @jaresty

**Comment by mattcui** [comment]
@dpb587-pivotal Hi Danny, we have this issue because faillog command has been widely used in our operation scripts, it always worked well on Trusty stemcell and earlier editions, we need to keep backward compatible after moving to Xenial stemcell, otherwise, there might meet operation problems. I will also check our operation team if it's easy to migrate to `pam_tally2`

**Comment by jaresty** [comment]
What version of the trusty stemcell are you using?
2018年8月18日(土) 0:40 Matt Cui <notifications@github.com>:

**Comment by jfmyers9** [comment]
Hey @mattcui,

We've gone ahead and validated that this hasn't worked on the trusty stemcell line since at least 3421. As mentioned by previous explorations above, it seems that the preferred tool is `pam_tally2` now which does appear to work.

We are going to close this issue. Feel free to reopen it if you have any more concerns.

Best,

@jfmyers9 && @jrussett, CF BOSH
