### ISSUE TITLE
Possible to update openssl to the latest version in the stemcell?

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-linux-stemcell-builder#62]
I know It's 1.0.2g-1ubuntu4.13 in [Ubuntu Xenial packages](https://packages.ubuntu.com/xenial-updates/openssl), but it's too old, published in 1 Mar 2016, there always has severe [vulnerabilities](https://www.openssl.org/news/vulnerabilities.html) in openssl, possible to always update to the latest version in the stemcell? Thanks.

/cc @dpb587-pivotal @edwardstudy

**Comment by luan** [comment]
Hi @mattcui,

We'd prefer to not stray away from what's provided by the standard xenial package since doing so would increase complexity in the process of building stemcells. Canonical tends to bump those packages when there is a *high* or *critical* severity CVE and that seems OK to us.

Do you have a specific reason you'd like to see that version bumped?

Best,
@luan & @mikexuu, CF BOSH Team

**Comment by mattcui** [comment]
@luan we always got vulnerability issues report about openssl from our security team, so in our SoftLayer stemcell, we have to upgrade it to the latest version.

**Comment by jfmyers9** [comment]
Hey @mattcui,

As mentioned by @luan, we rely on Canonical to provide us with updated security patches for the openSSL shipped in our Ubuntu stemcells.

For some reason, the version reported by `openssl version` has a much older date than the actual latest patch. However, you can see the up to date information for both packages here:
* Trusty: https://launchpad.net/ubuntu/+source/openssl/1.0.1f-1ubuntu2.26
* Xenial: https://launchpad.net/ubuntu/+source/openssl/1.0.2g-1ubuntu4.13

Both of these packages have been updated as recently as June 2018 and contain the most recent security fixes.

Best,

@jfmyers9, CF BOSH
