### ISSUE TITLE
[xenial] Support for multipath and open-iscsi

### ISSUE THREAD

**Issue by daniellavoie** [cloudfoundry/bosh-linux-stemcell-builder#87]
We would like to ease the effort required to integrate CFCR with iscsi storage.

An operation team I am working with is hoping to use Pure Storage with `iscsi` through vSphere datastores. To enable this, we need the following packages : 

* multipath-tools_0.5.0+git1.656f8865-5ubuntu2_amd64.deb
* open-iscsi_2.0.873+git0.3b4b4500-14ubuntu3_amd64.deb

I would be happy to provide a PR but wanted to discuss with you if that should be contributed in the upstream stemcell or in the CFCR bosh release.

**Comment by christarazi** [comment]
Do you still need these packages? If so, please re-open.

**Comment by tjvman** [comment]
A release's dependencies should be packaged in the release where possible. Doing so provides several benefits:
* More flexibility in how the dependency is configured
* Less overhead - stemcells have security compliance requirements that must be met, releases do not.
* Makes the release more portable; don't have to be on a version of the stemcell that has been updated to have the dependency
* Reduces the likelihood of conflicting with other releases because the packages are only installed on the VMs that need them, rather than *every* VM.
